# Generated by Django 3.2.9 on 2021-11-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20211101_1650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companie',
            new_name='Company',
        ),
    ]
